### ISSUE TITLE
Failed to resolve entry for package "react". The package may have incorrect main/module/exports specified in its package.json

### ISSUE THREAD

**Issue by alxhotel** [yusukebe/honox-playground#1]
I can't seem to run the react project:

```
Internal server error: Failed to resolve entry for package "react". The package may have incorrect main/module/exports specified in its package.json.
      at packageEntryFailure (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:48252:17)
      at resolvePackageEntry (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:48249:5)
      at tryNodeResolve (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:48027:20)
      at nodeImport (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:55035:26)
      at ssrImport (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:54946:30)
      at eval (/home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/@hono/react-renderer/dist/index.js:3:50)
      at instantiateModule (file:///home/alex/Documents/Projects/Random/Code/honox-playground/node_modules/vite/dist/node/chunks/dep-BBHrJRja.js:55006:15)

```

**Comment by yusukebe** [comment]
Hi @alxhotel 

Add `react` and `react-dom` to `ssr.external` .

```ts
export default defineConfig({
  ssr: {
    external: ['react', 'react-dom']
  },
  plugins: [honox(), pages()]
})
```

**Comment by alxhotel** [comment]
Perfect, it works! Thanks @yusukebe!
